version: "3.8"

services:
  # SERVIÇO 1: API Fake (JSON Server)
  # Simula o banco de dados de usuários para Login/Registro
  mock-api:
    container_name: dev_mock_api
    build:
      context: ./mock-api
      dockerfile: Dockerfile
    ports:
      - "3004:3004"
    volumes:
      - ./mock-api:/usr/src/app
    restart: always

  frontend:
    # SERVIÇO 2: Front-end (Vite + React)
    container_name: dev_frontend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    environment:
      VITE_API_URL: http://localhost:3004
      CHOKIDAR_USEPOLLING: "true"
    volumes:
      - ./src:/app/src
    depends_on:
      - mock-api
    restart: always
